"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import mimetypes
from pathlib import Path
import os
import dotenv
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

dotenv_file = os.path.join(BASE_DIR, ".env")

if os.path.isfile(dotenv_file):
    dotenv.load_dotenv(dotenv_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'smart_selects',
    'book',
    'stores',
    'users',
    'footer',
    'publishers',
]
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = '/home/nabilmokhtar/AL-AWAL/static'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# MEDIA_ROOT = '/home/nabilmokhtar/AL-AWAL/media'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = '/media/'

# LOGIN_URL = 'signupandlogin/'
# LOGIN_REDIRECT_URL = 'Home'
# LOGIN_URL = reverse_lazy('signupandlogin')
# LOGIN_REDIRECT_URL = reverse_lazy('')
# LOGOUT_REDIRECT_URL = '/'

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}


USE_DJANGO_JQUERY = True
X_FRAME_OPTIONS = 'SAMEORIGIN'

# SIMPLEUI

# SIMPLEUI_HOME_PAGE = 'https://www.baidu.com'
# SIMPLEUI_HOME_TITLE = 'My Home Title'
# SIMPLEUI_HOME_ICON = 'fa fa-user'

# SIMPLEUI_INDEX = 'https://www.88cto.com'

SIMPLEUI_LOGO = '/static/alawalredlogo.png'

SIMPLEUI_HOME_INFO = False
# SIMPLEUI_HOME_QUICK = False
# SIMPLEUI_HOME_ACTION = False

SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menus': [{
        'name': 'CATEGORY & SUBCATEGORY',
        'icon': 'fas fa-th-large',
        'models': [
            {
                'name': 'Category',
                'url': '/admin/store/category/',
                'icon': 'fas fa-th-list',
            },
            {
                'name': 'Subcategory',
                'url': '/admin/store/subcategory/',
                'icon': 'fas fa-sitemap',
            }],

    }, {
        'name': 'BOOK',
        'icon': 'fas fa-book',
        'models': [{
            'name': 'Book',
            'icon': 'fas fa-book',
            'url': '/admin/book/book/',
        }]
    }, {
        'name': 'PUBLISHERS',
        'icon': 'far fa-newspaper',
        'models': [{
            'name': 'Publisher',
            'icon': 'far fa-newspaper',
            'url': '/admin/publisher/publishers/',
        }]
    }, {
        'name': 'MY-INFORMATION',
        'icon': 'fas fa-id-card',
        'models': [{
            'name': 'MyInformation',
            'icon': 'fas fa-id-card',
            'url': '/admin/footer/myinformation/',
        }]
    }, {
        'name': 'PERMISSIONS',
        'icon': 'fas fa-shield-alt',
        'models': [{
            'name': 'Users',
            'icon': 'far fa-user',
            'url': '/admin/auth/user/',
        }, {
            'name': 'Groups',
            'icon': 'fas fa-users',
            'url': '/admin/auth/group/',
        }]
    }, {
        'name': 'ORDER',
        'icon': 'fas fa-shopping-cart',
        'models': [{
            'name': 'order',
            'icon': 'fas fa-shopping-cart',
            'url': '/admin/book/order/',
        }]
    }
    ]
}

# Settting Email:

EMAIL_BACKEND = os.environ['EMAIL_BACKEND']
EMAIL_HOST = os.environ['EMAIL_HOST']
EMAIL_HOST_USER = os.environ['EMAIL_HOST_USER']
EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']
EMAIL_USE_TLS = os.environ['EMAIL_USE_TLS']
EMAIL_PORT = os.environ['EMAIL_PORT']

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 86400  # Equivalent to 1 day
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
