# Generated by Django 3.1.4 on 2021-07-23 19:35

from django.db import migrations, models
import publishers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofsupplier', models.CharField(max_length=300, null=True)),
                ('logo', models.ImageField(null=True, upload_to=publishers.models.rename_image)),
                ('moreinformation', models.TextField(null=True)),
                ('websitelink', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Publishers',
            },
        ),
    ]
