# Generated by Django 3.1.4 on 2021-07-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(max_length=100)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instgram_link', models.URLField(blank=True, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'company contacts',
            },
        ),
    ]
